version: '3.5'
services:
  anderswind:
    image: awia/anderswind.dk
    container_name: anderswind.dk
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rekon-traefik_proxy"
      - "traefik.backend=anderswind"
      - "traefik.frontend.rule=Host:anderswind.dk"
    networks:
      - default
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
